//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfratWebApi.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsForRent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarsForRent()
        {
            this.RentsInfoes = new HashSet<RentsInfo>();
        }
    
        public int CarID { get; set; }
        public int TypeID { get; set; }
        public int CarNumber { get; set; }
        public double KM { get; set; }
        public bool GoodForRent { get; set; }
        public bool AvalibleForRent { get; set; }
        public int BranchID { get; set; }
        public bool Available { get; set; }
        public string Base64Image { get; set; }
        public string ImageType { get; set; }
        public string Model { get; set; }
        public double CostPerDay { get; set; }
        public double CostPerDayDelay { get; set; }
        public string Gere { get; set; }
        public Nullable<int> YearOfProduce { get; set; }
        public string ManufactorName { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual CarsType CarsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentsInfo> RentsInfoes { get; set; }
    }
}
