//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfratWebApi.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarsType()
        {
            this.CarsForRents = new HashSet<CarsForRent>();
        }
    
        public int TypeID { get; set; }
        public string Model { get; set; }
        public double CostPerDay { get; set; }
        public double CostPerDayDelay { get; set; }
        public string Gere { get; set; }
        public Nullable<int> YearOfProduce { get; set; }
        public string ManufactorName { get; set; }
        public Nullable<int> PhotoID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsForRent> CarsForRents { get; set; }
        public virtual Photo Photo { get; set; }
    }
}
